#!/usr/bin/perl -wT
 # vim: ft=xml ts=4 sw=4 et:
 #----------------------------------------------------------------------
 # heading     : Bandwidth Management
 # description : Authentication
 # navigation  : 3000 3250
 #----------------------------------------------------------------------
 use strict;
 use esmith::TestUtils;
 use esmith::FormMagick::Panel::bwlimit_ldapauth;

 my $fm = esmith::FormMagick::Panel::bwlimit_ldapauth->new();

 $fm->display();

 __DATA__
 <form title="FORM_TITLE"
     header="/etc/e-smith/web/common/head.tmpl"
     footer="/etc/e-smith/web/common/foot.tmpl">

     <page name="First" pre-event="print_status_message()" post-event="modify_ldap_settings()">

         <description>FORM_DESCRIPTION</description>
         
         <field type="select"
            id="ldap_enabled"
            options="'yes' => 'Yes', 'no' => 'No'" value="get_ldap_opt_value('ldap_enabled')">
            <label>LABEL_BWLIMIT_LDAP_ENABLED</label>
         </field>


         <field type="text" id="ldap_binddn" value="get_ldap_opt_value('ldap_binddn')">
            <label>LABEL_BWLIMIT_BINDDN</label>
         </field>

         <field type="text" id="ldap_bindpass" value="get_ldap_opt_value('ldap_bindpass')">
            <label>LABEL_BWLIMIT_BINDPASS</label>
         </field>

         <field type="text" id="ldap_server" value="get_ldap_opt_value('ldap_server')">
            <label>LABEL_BWLIMIT_LDAPSERVER</label>
         </field>

         <field type="text" id="ldap_basedn" value="get_ldap_opt_value('ldap_basedn')">
            <label>LABEL_BWLIMIT_BASEDN</label>
         </field>

         <field type="select" id="ldap_autoadd" options="'yes' => 'Yes', 'no' => 'No'" value="get_ldap_opt_value('ldap_autoadd')">
            <label>LABEL_BWLIMIT_LDAPAUTOADD</label>
         </field>

         <field type="text" id="ldap_port" value="get_ldap_opt_value('ldap_port')">
            <label>LABEL_BWLIMIT_LDAPPORT</label>
         </field>
         
         <field type="select" id="ldap_usessl" options="'yes' => 'Yes', 'no' => 'No'" value="get_ldap_opt_value('ldap_usessl')">
            <label>LABEL_BWLIMIT_LDAPSSL</label>
         </field>

         <field type="select" id="ldap_checkcert" options="'yes' => 'Yes', 'no' => 'No'" value="get_ldap_opt_value('ldap_checkcert')">
            <label>LABEL_BWLIMIT_CHECKCERT</label>
         </field>

         <field type="text" id="ldap_searchfilter" value="get_ldap_opt_value('ldap_searchfilter')">
            <label>LABEL_BWLIMIT_LDAPSEARCHFILTER</label>
            <description>LABEL_BWLIMIT_LDAPFILTERDESC</description>
         </field>

         <field type="text" id="ldap_usernamefield" value="get_ldap_opt_value('ldap_usernamefield')">
            <label>LABEL_BWLIMIT_USERNAMEFIELD</label>
            <description>LABEL_BWLIMIT_LDAPUSERNAMEDESC</description>
         </field>

         <field type="text" id="ldap_firstnamefield" value="get_ldap_opt_value('ldap_firstnamefield')">
            <label>LABEL_BWLIMIT_FIRSTNAMEFIELD</label>
         </field>

         <field type="text" id="ldap_secondnamefield" value="get_ldap_opt_value('ldap_secondnamefield')">
            <label>LABEL_BWLIMIT_SECONDNAMEFIELD</label>
         </field>

         <field type="text" id="ldap_mailfield" value="get_ldap_opt_value('ldap_mailfield')">
            <label>LABEL_BWLIMIT_MAILFIELD</label>
         </field>

          <subroutine src="print_button('SAVE')" />

     </page>

     
 </form>


